# Generated by Django 3.1.4 on 2021-11-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produt_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('app', 'App'), ('card', 'Card'), ('web', 'Web')], max_length=50)),
                ('product_picture', models.ImageField(upload_to='images/')),
                ('product_client', models.CharField(max_length=100)),
                ('product_date', models.DateField()),
                ('product_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produt_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('app', 'App'), ('card', 'Card'), ('web', 'Web')], max_length=50)),
                ('product_picture', models.ImageField(upload_to='images/')),
                ('product_client', models.CharField(max_length=100)),
                ('product_date', models.DateField()),
                ('product_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammate_name', models.CharField(max_length=100)),
                ('teammate_photo', models.ImageField(upload_to='images/')),
                ('teammate_job', models.CharField(max_length=100)),
                ('teammate_twitter', models.URLField()),
                ('teammate_facebook', models.URLField()),
                ('teammate_instagram', models.URLField()),
                ('teammate_linkedln', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produt_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('app', 'App'), ('card', 'Card'), ('web', 'Web')], max_length=50)),
                ('product_picture', models.ImageField(upload_to='images/')),
                ('product_client', models.CharField(max_length=100)),
                ('product_date', models.DateField()),
                ('product_url', models.URLField()),
            ],
        ),
    ]
