# Generated by Django 3.1.4 on 2021-11-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='produt_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='produt_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='web',
            old_name='produt_name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='app',
            name='product_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
