# Generated by Django 3.1.4 on 2021-11-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211117_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='product_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='product_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
