# Generated by Django 3.1.4 on 2022-08-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211117_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='teammate_facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='teammate_instagram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='teammate_linkedln',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='teammate_twitter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
